language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "pip install -r testing-requirements.txt"
# command to run tests
script:
  - tests/run_tests.sh